alias be="bundle exec"
alias bu="bundle update"
alias bi="bundle install"
alias bs="bundle show"
alias bv="bundle install --path vendor"
alias foremandev="foreman start -f Procfile.development"
alias fd="foreman start -f Procfile.development"
